"""Add new tables - Class and DataSend_#2

Revision ID: 20f487a12444
Revises: 2cf37d49ae51
Create Date: 2024-12-04 07:22:31.023053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f487a12444'
down_revision: Union[str, None] = '2cf37d49ae51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('man_class', sa.String(), nullable=False))
    op.add_column('classes', sa.Column('count_ill', sa.Integer(), nullable=False))
    op.add_column('classes', sa.Column('count_class', sa.Integer(), nullable=False))
    op.add_column('classes', sa.Column('proc_ill', sa.Integer(), nullable=False))
    op.add_column('classes', sa.Column('closed', sa.Boolean(), nullable=False))
    op.add_column('classes', sa.Column('date_closed', sa.Date(), nullable=False))
    op.add_column('classes', sa.Column('date_open', sa.Date(), nullable=False))
    op.add_column('classes', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('datasends', sa.Column('date_send', sa.Date(), nullable=False))
    op.add_column('datasends', sa.Column('count_all_ill', sa.Integer(), nullable=False))
    op.add_column('datasends', sa.Column('count_all', sa.Integer(), nullable=False))
    op.add_column('datasends', sa.Column('count_class_closed', sa.Integer(), nullable=False))
    op.add_column('datasends', sa.Column('count_ill_closed', sa.Integer(), nullable=False))
    op.add_column('datasends', sa.Column('count_all_closed', sa.Integer(), nullable=False))
    op.add_column('datasends', sa.Column('sending', sa.Boolean(), nullable=False))
    op.drop_constraint('datasends_name_class_key', 'datasends', type_='unique')
    op.create_unique_constraint(None, 'datasends', ['date_send'])
    op.drop_column('datasends', 'name_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasends', sa.Column('name_class', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'datasends', type_='unique')
    op.create_unique_constraint('datasends_name_class_key', 'datasends', ['name_class'])
    op.drop_column('datasends', 'sending')
    op.drop_column('datasends', 'count_all_closed')
    op.drop_column('datasends', 'count_ill_closed')
    op.drop_column('datasends', 'count_class_closed')
    op.drop_column('datasends', 'count_all')
    op.drop_column('datasends', 'count_all_ill')
    op.drop_column('datasends', 'date_send')
    op.drop_column('classes', 'date')
    op.drop_column('classes', 'date_open')
    op.drop_column('classes', 'date_closed')
    op.drop_column('classes', 'closed')
    op.drop_column('classes', 'proc_ill')
    op.drop_column('classes', 'count_class')
    op.drop_column('classes', 'count_ill')
    op.drop_column('classes', 'man_class')
    # ### end Alembic commands ###
