"""Add new tables - Class and DataSend_

Revision ID: 2cf37d49ae51
Revises: bd90cd1bf4ff
Create Date: 2024-12-04 06:33:53.920209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf37d49ae51'
down_revision: Union[str, None] = 'bd90cd1bf4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
