"""Refact Tables2

Revision ID: 9a47abc8b9a2
Revises: 7558e0f5de43
Create Date: 2024-10-22 12:54:14.279406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a47abc8b9a2'
down_revision: Union[str, None] = '7558e0f5de43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
