"""Edit tables Dish

Revision ID: b15045616c0f
Revises: e43b19b9b1e7
Create Date: 2024-10-22 11:58:47.874999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b15045616c0f'
down_revision: Union[str, None] = 'e43b19b9b1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('calories', sa.Float(), nullable=False))
    op.add_column('dishes', sa.Column('protein', sa.Float(), nullable=False))
    op.add_column('dishes', sa.Column('fats', sa.Float(), nullable=False))
    op.add_column('dishes', sa.Column('carb', sa.Float(), nullable=False))
    op.drop_column('dishes', 'prop_dish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('prop_dish', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('dishes', 'carb')
    op.drop_column('dishes', 'fats')
    op.drop_column('dishes', 'protein')
    op.drop_column('dishes', 'calories')
    # ### end Alembic commands ###
