"""Add table Dish new column - section

Revision ID: d16871d2260e
Revises: 49b35d294ded
Create Date: 2024-11-16 17:37:53.806001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16871d2260e'
down_revision: Union[str, None] = '49b35d294ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('section', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'section')
    # ### end Alembic commands ###
