"""Add table Dish new column - section_3

Revision ID: e2ff92242aa7
Revises: 91c18837dd87
Create Date: 2024-11-16 17:47:26.685911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ff92242aa7'
down_revision: Union[str, None] = '91c18837dd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'section',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'section',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
